### ISSUE TITLE
Support for Futures and flatMap for client stub

### ISSUE THREAD

**Issue by TaufeqRazakh** [googleapis/gapic-generator-kotlin#33]
Is it okay to assume that there is a possibility to refactor/generate client libraries in a way that when writing client stub a channel can be established by the use of `Futures` and `flatMap` instead of using `runBlocking{...}`. 

I'm hoping this would conform to the idiomatic way of Kotlin and also make the process of writing server and client code much easier.

If this is something of interest, I would love to participate in implementing a similar feature.

**Comment by jbolinger** [comment]
We're still reviewing how the client libraries should look, so we are certainly open to new ideas. I'm not sure if I understand what you're proposing though. Would you mind coming up with a few examples to illustrate?

Currently, the generator uses suspending functions as outlined in the [coroutines guide](https://kotlinlang.org/docs/reference/coroutines/coroutines-guide.html) instead of futures, promises, etc. (which actually discourages the use of futures). The `runBlocking` bit is admittedly odd, but it's really only useful for examples anyway (I need to write better examples...). In a real application you'd use the suspend functions exposed by the client with `launch`, `async`, etc. to get a `Deferred`, compose multiple operations, and do the same things that are associated with a Future in other languages.

**Comment by TaufeqRazakh** [comment]
Please apologize for not being clear about my idea. I was hoping for an implementation of the client code such as 
```
fun runExample() = {
  // create a client with an insecure channel
  val channelLoc = ManagedChannelBuilder.forAddress("localhost", 8080)
  val client : Future[SuccessfullConnection] = HelloServiceClient.create(channelLoc) match {
   case Success {
     ??? //run query here
   }
  case _ { ??? //Display an error }
  }
}
```
But as you mentioned about the freedom to use exposed suspended functions for the client, I guess the sample implementation is also possible. 
Would it be wise to make some functionality of io.grpc.ManagedChannelBuilder a part of the "HelloServiceClient" class. Thus it would be easier to assign port and build the server from the same class object. 
`val client = HelloServiceClient.create(channel = ("localhost", 8080)).usePlaintext().build()`

**Comment by jbolinger** [comment]
I don't think there's much reason to wrap the methods that create clients in any type of async mechanism. Those are local operations so they should fail fast and either return the client or throw an exception. Do you think there's a benefit to it? What would the use case be?

More generally, though it's already possible to wrap anything like that in a future if someone really wants to i.e.

```kotlin
val client = MyClient.create(...)
val future = future {
  val x = client.doSomething(...)
  val y = client.doSomethingElse(...)
  x + y
}
```

**Comment by TaufeqRazakh** [comment]
Thanks for the example with the futures implementation. My knowledge with Kotlin style is limited and I tend to fall back on Scala for this.

I was hoping injecting the methods to the ServiceClient will reduce the import lines. I was also hoping that by applying pattern matching one can write custom error messages when establishing connection. Do you think something along these lines would be of interest towards ideas for client libraries ?

**Comment by jbolinger** [comment]
Sure, we're hoping to get some docs up on this repo to discuss options before anything is finalized but it'll take awhile for all of that to get going and stabilize. Please get involved if you're interested!

On the other hand, if you have ideas feel free to keep commenting here or open new issues and we'll work through them. No reason we have to wait for everyone else to start discussing if you've got ideas now.
