### ISSUE TITLE
Automatic Auth using GOOGLE_APPLICATION_CREDENTIALS?

### ISSUE THREAD

**Issue by bshaffer** [googleapis/gapic-generator-kotlin#5]
Hey Joe!
Looking at your sample [here](https://github.com/googleapis/gapic-generator-kotlin/blob/master/example-api-clients/app/src/main/java/com/google/api/examples/kotlin/client/MainActivity.kt), is it required to build the `TokenFactory` to retrieve a kotlin gapic client? This is not something required in the Java client libraries, so I'm curious if I'm just misreading it, or if it's implemented differently here.

This library:
```kt
val tokenFactory = applicationContext.resources.openRawResource(R.raw.sa).use {
    AccessTokens(it, LanguageServiceClient.ALL_SCOPES)
}

// create a client with an access token
client = LanguageServiceClient.fromAccessToken(tokenFactory.fetchToken())
``` 

Java equivalent:
```kt
client = LanguageServiceClient()
```

**Comment by jbolinger** [comment]
It's possible to use a service account now. See this example:

https://github.com/googleapis/gapic-generator-kotlin/blob/78b6b7217a6f5a8cd82bd342c824de394e8da9fe/example-api-clients/app/src/main/java/com/google/api/examples/kotlin/client/MainActivityOn.kt#L36-L42

Click though for the full example, which is exactly the same as the one that you linked but using a service account instead of a token factory.

There is no zero argument constructor that relies on an environment variable like `GOOGLE_APPLICATION_CREDENTIALS` as in the Java example that you provided, but I can certainly add one. 

I suspect that the reason this example is little confusing now is because we started with Android in mind and the Cloud API's don't have a good authentication method to use on that platform outside fo the Firebase clients (i.e. the zero arg constructor doesn't really make sense there and, similarly, the token factory doesn't make sense for a server-side app). The token factory thing is ugly, but using a service account in a mobile app is even worse in most cases. For a server side app you'd just change the example code I posted to something like the following:

```kotlin
client = LanguageServiceClient(getResourceAsStream("my_account.json"))
```

and we can add a default to get the zero arg version from a variable.

I'm considering something like a flag or config option(s) for things like this. For example, I don't want the generator to create a constructor that relies on `GOOGLE_APPLICATION_CREDENTIALS` unless it's both a Google API and a server-side library. But it's early days, so if you have thoughts on how it should work I'd be interested them.

**Comment by jbolinger** [comment]
I added some server side examples a few weeks ago to show how this works with `GOOGLE_APPLICATION_CREDENTIALS` now:

https://github.com/googleapis/gapic-generator-kotlin/blob/5df086a27bacc7bee0da8daab8bfe1d0cc288aa8/example-api-cloud-clients/src/main/kotlin/example/Language.kt#L33
